#! /usr/bin/env python3

import os

from pathlib import Path

MAIN_PATH = Path(os.path.dirname(os.path.realpath(__file__)))

HOMEWORK_PASSWORDS = {
    's3cr3t': 'hw1',
    '7hLhMc5L7xJRn26J': 'hw2',
    '34s13r_p4ssw0rd': 'hw3',
}

def main():
    password = input("Assignment Password: ")
    if password in HOMEWORK_PASSWORDS:
        hw = HOMEWORK_PASSWORDS[password]
        path = str(MAIN_PATH / hw / 'user_wrapper')
        os.system(f'su {hw} -c "{path}"')
    else:
        print("Wrong password! Check the mailing list.")
        return

if __name__ == '__main__':
    main()
